error_codes <- list(
  vbp_not_linear = 'Error in VBP analysis, cost was not a linear function of price. This typically means you have selected the wrong parameter.',
  vbp_affects_outcomes = 'Error in VBP analysis, price parameter should not affect outcomes. This typically means you have selected the wrong parameter.',
  duplicate_param_in_scenario = 'Error in scenario "{scenario_name}", parameter "{parameter_name}" is used more than once.',
  scenario_wrong_datatype = 'Error in scenario analysis, scenarios be provided as a data.frame object.',
  scenario_null = 'Error in scenario analysis, no scenarios were defined.',
  scenario_missing_name = 'Error in scenario analysis, scenario was missing name.',
  scenario_missing_param_name = 'Error in scenario "{scenario_name}", missing parameter name.',
  scenario_missing_value = 'Error in scenario "{scenario_name}", parameter "{parameter_name}" is missing value.',
  syntax_error = 'Syntax error in {context}.',
  state_group_wrong_col_type = 'Error in state group specification. Column "{col}" must be of type {type}.',
  state_group_wrong_type = 'Error in state group specification, must be provided as data.frame with columns for "name", "state_group", and "share".',
  state_group_bad_names = 'Error in state group specification, invalid states referenced: {names}.',
  patch_model_bad_key = 'Error in patch_model, key "{key}" already exists on model.',
  zero_initial_prob = 'Initial state probabilities must be defined.',
  twsa_bad_format = 'Invalid format for two-way sensitivity analysis.',
  twsa_empty = 'Two-way sensitivity analysis must be configured before running.',
  twsa_wrong_no_params = 'Two-way sensitivity analyses must include exactly two parameters per analysis.',
  twsa_params_empty = 'Two-way sensitivity analysis must be configured before running.',
  twsa_params_dne = 'Two-way sensitivity analysis references missing parameters: {params}.',
  twsa_param_orphaned = 'Two-way sensitivity analysis includes parameters that are not part of any analysis: {params}.',
  twsa_param_bad_type = 'Parameters in two-way sensitivity analyses configured with invalid method for specifying values: {params}.',
  twsa_group_strat_dep = 'Two-way sensitivity analysis may not vary parameters that are group or strategy dependent.',
  vbp_settings_undefined = 'VBP settings have not been configured.'
)