# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_convert_tables <- function(matrices, names) {
    .Call('_heRomod_cpp_convert_tables', PACKAGE = 'heRomod', matrices, names)
}

